"""empty message

Revision ID: 245fea3a61c4
Revises: ff5c4523d0d4
Create Date: 2022-06-05 19:27:34.069604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245fea3a61c4'
down_revision = 'ff5c4523d0d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('watch_date', sa.String(), nullable=True))
    op.drop_index('ix_movies_name', table_name='movies')
    op.drop_column('movies', 'date')
    op.drop_column('movies', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('movies', sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_movies_name', 'movies', ['name'], unique=False)
    op.drop_column('movies', 'watch_date')
    # ### end Alembic commands ###
