---
- name: Network Getting Started First Playbook
  hosts: mikrus
  tasks:
    - name: pwd
      command: git pull
      args:
        chdir: /root/inventory-be
    - name: pwd
      command: docker stop inv
      args:
        chdir: /root/inventory-be
    - name: pwd
      command: docker container rm  inv
      args:
        chdir: /root/inventory-be
    - name: pwd
      command: docker-compose -f deployment/prod/docker-compose.yml up inv -d
      args:
        chdir: /root/inventory-be
