# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - "**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    # TODO add pip cache
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker build -f ./deployment/Dockerfile --tag uszczi/inventory_be  .
          docker push uszczi/inventory_be

  deploy:
    needs: [build_and_push]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          sudo apt install ansible openssh-server sshpass
          cd ansible
          echo ${{ secrets.ANSIBLE_VAULT_PASS }} >> secret
          ansible -e @secrets.yml  --vault-password-file secret -m ping mikrus
          ansible-playbook -e @secrets.yml  --vault-password-file secret deploy.yml
