name: Main workflow

on:
  push:
    branches:
      - "main"

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Trigger deploy via Ansible
        run: |
          sudo apt install ansible openssh-server sshpass
          cd ansible
          echo ${{ secrets.ANSIBLE_VAULT_PASS }} >> secret
          ansible-playbook -e @secrets.yml  --vault-password-file secret deploy.yml
