name: Main workflow

on:
  push:
    branches:
      - "**"

  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    # TODO add pip cache and check timing
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker build -f ./deployment/Dockerfile --tag uszczi/inventory_be  .
          docker push uszczi/inventory_be

  deploy:
    needs: [build_and_push]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          sudo apt install ansible openssh-server sshpass
          cd ansible
          echo ${{ secrets.ANSIBLE_VAULT_PASS }} >> secret
          ansible-playbook -e @secrets.yml  --vault-password-file secret deploy.yml
